name: Send Email Notification

on:
  push:
    branches:
      - main # or 'master'
  workflow_dispatch:

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          # server_address: ${{ secrets.MAIL_SERVER_SMTP }}
          # server_port: ${{ secrets.MAIL_SERVER_PORT }}
          # username: ${{ secrets.EMAIL_USERNAME }}
          # password: ${{ secrets.EMAIL_PASSWORD }}
          # subject: "Build job of ${{github.repository}} completed successfully!"
          # to: ${{ secrets.EMAIL_TO }}
          # from: Github Notif
          # body: "A new commit has been pushed!"
          # secure: true # or false for no SSL
          # ignore_cert: true
          # convert_markdown: true
          # priority: low

          # Specify connection via URL (replaces server_address, server_port, secure,
          # username and password)
          #
          # Format:
          #
          #  * smtp://user:password@server:port
          #  * smtp+starttls://user:password@server:port
          connection_url: smtp://${{secrets.EMAIL_USERNAME}}:${{secrets.EMAIL_PASSWORD}}@${{secrets.MAIL_SERVER_SMTP}}:${{secrets.MAIL_SERVER_PORT}}
          # Required mail server address if not connection_url:
          #   server_address: ${{secrets.MAIL_SERVER_SMTP}}
          # Server port, default 25:
          #   server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          # username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          # password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions job result
          # Required recipients' addresses:
          to: ${{ secrets.EMAIL_TO }}
          # Required sender full name (address can be skipped):
          from: ${{ secrets.EMAIL_FROM }}
          # Optional plain body:
          body: Build job of ${{github.repository}} completed successfully!
          # Optional HTML body read from file:
          # html_body: file://README.html
          # Optional carbon copy recipients:
          # cc: kyloren@example.com,leia@example.com
          # Optional blind carbon copy recipients:
          # bcc: r2d2@example.com,hansolo@example.com
          # Optional recipient of the email response:
          # reply_to: ${{ secrets.EMAIL_TO }}
          # Optional Message ID this message is replying to:
          # in_reply_to: <random-luke@example.com>
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # Optional converting Markdown to HTML (set content_type to text/html too):
          convert_markdown: true
          # Optional attachments:
          # attachments: attachments.zip,git.diff,./dist/static/*.js
          # Optional priority: 'high', 'normal' (default) or 'low'
          priority: low
          # Optional nodemailerlog: true/false
          #   nodemailerlog: false
          # Optional nodemailerdebug: true/false if true lognodem will also be set true
          #   nodemailerdebug: false
